name: Go

on:
  push:
    branches:
      - main
    paths-ignore:
      - "ui/**"

permissions:
  contents: read

jobs:
  gen:
    name: 'git state after "make gen protobuf"'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: nicknovitski/nix-develop@v1.2.1
      - name: 'Check for dirty Git state after running "make gen protobuf"'
        run: |
          make gen protobuf
          git diff
          git diff --name-only --exit-code
